2021-08-21 11:30:26,016 [-] [PassThroughMessageProcessor-2]  WARN __SynapseService ERROR_CODE : 101503 ERROR_MESSAGE : Error while connecting to the endpoint (Connection Failed)
2021-08-21 11:30:26,016 [-] [PassThroughMessageProcessor-2]  INFO __SynapseService FaultHandler executing impl: org.apache.synapse.mediators.MediatorFaultHandler
2021-08-21 11:30:26,016 [-] [PassThroughMessageProcessor-2]  WARN __SynapseService Executing fault sequence mediator : fault
2021-08-21 11:30:26,039 [-] [PassThroughMessageProcessor-2]  INFO __SynapseService To: http://localhost:8280/, WSAction: urn:getQuote, SOAPAction: urn:getQuote, ReplyTo: http://www.w3.org/2005/08/addressing/anonymous, MessageID: urn:uuid:485d3be1-af8b-42dc-9b9f-1157ec7a3e24, Direction: request, MESSAGE = Executing default "fault" sequence, ERROR_CODE = 101503, ERROR_MESSAGE = Error while connecting to the endpoint (Connection Failed), Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header xmlns:wsa="http://www.w3.org/2005/08/addressing"/><soapenv:Body><m0:getQuote xmlns:m0="http://services.samples"><m0:request><m0:symbol>IBM</m0:symbol></m0:request></m0:getQuote></soapenv:Body></soapenv:Envelope>
